CreateThread(function()
    AddTextEntry("NIKEZTATTOOS_TAT_000_M", "Seaside Dark Chest")
    AddTextEntry("NIKEZTATTOOS_TAT_001_M", "Seaside Colored Chest")
    AddTextEntry("NIKEZTATTOOS_TAT_002_M", "Seaside Linework Back")
    AddTextEntry("NIKEZTATTOOS_TAT_003_M", "Seaside Back")
    AddTextEntry("NIKEZTATTOOS_TAT_004_M", "Seaside Right Arm")
    AddTextEntry("NIKEZTATTOOS_TAT_005_M", "Seaside Left Leg")
    AddTextEntry("NIKEZTATTOOS_TAT_006_M", "Seaside Right Leg")
    AddTextEntry("NIKEZTATTOOS_TAT_000_F", "Seaside Left Shoulder")
    AddTextEntry("NIKEZTATTOOS_TAT_001_F", "Seaside Color Left Shoulder")
    AddTextEntry("NIKEZTATTOOS_TAT_002_F", "Seaside Upper Thigh")
    AddTextEntry("NIKEZTATTOOS_TAT_003_F", "Seaside Left Calf")
    AddTextEntry("NIKEZTATTOOS_TAT_004_F", "Seaside Left Calf")
    AddTextEntry("NIKEZ_TAT_HUGINN_L", "Huginn, Facing Left")
    AddTextEntry("NIKEZ_TAT_HUGINN_R", "Huginn, Facing Right")
    AddTextEntry("NIKEZ_TAT_ATHENA", "Athena")
    AddTextEntry("NIKEZ_TAT_ODEN", "Odin and Huginn")
    AddTextEntry("NIKEZ_TAT_5STARLEMONS", "5 Star Lemons")
end)