fx_version 'cerulean'
games { 'gta5' }

this_is_a_map 'yes'

data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/np_apartments_room_int.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/np_h_int.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_61.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_44.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_72.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_16.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_49.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_24.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/ex_int_office_03b_dlc.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_38.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/bkr_biker_dlc_int_ware05.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/empty_house.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_36.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/v_int_53.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/interiors/ytyp/hei_dlc_apart_high2_new.ytyp'
